### ISSUE TITLE
How and where to configure

### ISSUE THREAD

**Issue by a412h** [sublimelsp/LSP-ruff#60]
I have followed the installation procedure.
Where do I configure Ruff for Sublimetext ?
Should I configure the file accessible from: Package Settings -> LSP -> Servers -> LSP-ruff ?
More precisely I need to lint following Flake8 and Pycodestyle, for example automatic detection of warnings, like W291.
How and where do I do that ?

**Comment by LDAP** [comment]
You configure ruff-lsp like you configure ruff, see https://docs.astral.sh/ruff/configuration/

**Comment by a412h** [comment]
A concrete example would be greatly appreciated.

**Comment by LDAP** [comment]
> Ruff can be configured through a pyproject.toml, ruff.toml, or .ruff.toml file.

Contents: 

```toml
[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "W"]
# -----add this-----------------^
```
