### ISSUE TITLE
2.0.0 seems to ignore "configuration" setting key

### ISSUE THREAD

**Issue by munkybutt** [sublimelsp/LSP-ruff#66]
Hey - with the latest update I have migrated across to the new settings but it seems like my "ruff.toml" file is ignored.
I noticed my imports were no longer being sorted according to my isort rules and the behaviour remains the same if the "configuration" key is commented out or not.
These are my settings:

```json
{
	"initializationOptions": {
		"globalSettings": {
                        "configuration": "D:/p4/tools/dcc_tools/mg_tools/.projects/ruff.toml",
			"showNotification": "on",
			"organizeImports": true,
			"fixAll": true,
		},
	}
}
```
To confirm, the ruff.toml path does exist and it was working with the previous lsp-ruff version yesterday.

This is the contents of my ruff.toml
```toml
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyi",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 100
indent-width = 4

# Assume Python 3.10
target-version = "py310"

[lint]
select = ["E", "F", "I"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
combine-as-imports = false
force-single-line = true
lines-between-types = 1
no-sections = true
required-imports = ["from __future__ import annotations"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
```

Any help would be appreciated
